# Generated by Django 5.2.4 on 2025-07-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatoruser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
