# Generated by Django 5.2.4 on 2025-07-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_calculatoruser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatoruser',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='calculatoruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='calculatoruser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='calculatoruser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Adminitrador'),
        ),
        migrations.AlterField(
            model_name='calculatoruser',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
    ]
