# Generated by Django 5.2.4 on 2025-07-27 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(max_length=128, verbose_name='Expressão')),
                ('result', models.CharField(max_length=128, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
